name = "cfw-diesel"
main = "app.js"
compatibility_date = "2025-09-23"

# If you need Node.js APIs
compatibility_flags = ["nodejs_compat"]

[vars]
API_KEY = "123456"

[[kv_namespaces]]
binding = "MY_KV"
id = "YOUR_KV_NAMESPACE_ID"