name: Ci of Diesel-project

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build our Diesel-core
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Cache Bun installation
      - name: Cache Bun
        id: cache-bun
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bunfig.toml') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      
      # Install Bun if it's not cached
      - name: Install Bun
        run: |
          if [ ! -d "$HOME/.bun" ]; then
          curl -fsSL https://bun.sh/install | bash
          fi
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
        continue-on-error: true # Allows the workflow to continue even if Bun is already installed

      - name: Install dependencies
        run: bun install
      
      - name: Run TypeScript Compiler
        run: tsc --noEmit || true

      - name: Minify our code
        run: bun run build

      - name: Run server and Test Application
        env:
          PORT: 3001
        run: bun test
        